### ISSUE TITLE
[Feature request] Allow to use a custom models directory

### ISSUE THREAD

**Issue by ke1ne** [axodox/unpaint#14]
...so user can load existing models instead of copying them to the deafult directory on C:\.
Thank you!

**Comment by danstis** [comment]
I also tested adding a junction point to an external models folder, but that also does not work.

**Comment by axodox** [comment]
That might be a limitation of the UWP container, it cannot access your drive with the current permissions which are declared in the  manifest. I wanted to keep the permissions minimal, for future MS store publishing, but I could also compile a non-MS store version (which might not even be UWP) and can do more, but I will check if there are UWP ways to get this as well.

**Comment by Aptronymist** [comment]
Yeah, I highly second this. Installing a certificate and being forced to download a specific model to a specific location is not a good way to start off someone's software experience. I have pretty limited space on my C: drive, but plenty elsewhere.
I can convert tons of pytorch models with other software, but I have no way of storing them all in that folder, nor would I even let myself be restricted by that kind of thing in the first place.

**Comment by alex-aparin** [comment]
Yeah, I also have the same issue. Unpaint does not recognize custom models copied into models folder. Unfortunately loading of model from application takes long time

**Comment by axodox** [comment]
I have looked into it last weekend, it seems that outside folder is actually solvable in UWP as well, as long the user selects it from the Windows folder selector dialog and some security tokens are stored.

The models have to be in ONNX format, and should be generated using [this](https://github.com/microsoft/Olive/tree/main/examples/directml/stable_diffusion) tool.

**Comment by alex-aparin** [comment]
@axodox Yep. I have ran unpaint. The only important thing is the correct model identifier, it's should be placed in unpaint.json file. After that Unpaint app correctly loaded custom model. AWESOME app! thank you

**Comment by axodox** [comment]
I have added the capability to use models outside the app data directory:
![image](https://github.com/axodox/unpaint/assets/22882208/97870501-b3b2-404a-bcd4-7ffc6cb21205)

**Comment by axodox** [comment]
It also possible to import arbitrary models from Hugging Face now - as long as they are compatible (most are not, however I have also created a guide to convert existing models: https://github.com/axodox/unpaint/wiki/Model-import):
![image](https://github.com/axodox/unpaint/assets/22882208/be5b4e43-a272-4708-8cab-e7d2d5747385)

**Comment by axodox** [comment]
I will submit the app to the store this weekend, which should solve the auto-updates and the certificate issues.
