### ISSUE TITLE
[Bug] Nvidia device being ignored (but works forcibly)

### ISSUE THREAD

**Issue by ke1ne** [axodox/unpaint#16]
I have an integrated AMD and discrete Nvidia graphics (laptop). By default, Unpaint uses AMD, and it don't "see" Nvidia at all.
However, I was able to force it in Windows Graphics settings, and after that, it worked.
P.S. It could be useful to show some system info in Settings section or something; like GPU detected, RAM/VRAM used, etc.

**Comment by axodox** [comment]
Yes, absolutely GPU select will be added.

Does AMD work, I do not have any AMD HW, although it worked today on the Xbox.

**Comment by ke1ne** [comment]
> Does AMD work?

Well, it hanged and crashed on some denoising stage.

**Comment by rt121212121** [comment]
I have the same setup, with Ryzen 7 5000 series and RTX 3700 laptop. It just errored confusingly with "generation failed". Going into graphics settings and selecting store applications then unpaint and setting it to Nvidia worked as described above. The images look like something distorted out of a nightmare for me but probably PEBKAC, not as nice as yours :-)

**Comment by Bravesun** [comment]
Same here. Integrated AMD Radeon GPU (power saving) with an Nvidia 3070 laptop GPU (high performance). I get "Generation Failed" immediately.
Followed the steps above to change the GPU to the Nvidia one in the Windows graphics settings and it works perfectly.

**Comment by axodox** [comment]
I will add a GPU selector when I have some time.

**Comment by axodox** [comment]
It will look like this (CI still going):
![image](https://github.com/axodox/unpaint/assets/22882208/bcef686e-b0ae-400a-8388-4bf4d9722299)

**Comment by axodox** [comment]
Ready to download.

**Comment by ke1ne** [comment]
@axodox works!
