### ISSUE TITLE
[Bug] Glitchy window header, and UI "blinks"

### ISSUE THREAD

**Issue by ke1ne** [axodox/unpaint#17]
On Windows 11, app header works glitchy. I'm using the Light mode, and Min/Max/Close buttons are not visible without mouse hovering:
![image](https://github.com/axodox/unpaint/assets/8934421/acbb6e60-2657-4f66-835c-472ced4bc202)

Also, the whole app content (UI, image) randomly (not often) blinks.

**Comment by axodox** [comment]
That is weird I have not seen that yet. I will check it later.

**Comment by axodox** [comment]
Fixed both issues, a new version will be uploaded once the CI pipeline finishes

**Comment by ke1ne** [comment]
Seems to be ok. Thanks!
