### ISSUE TITLE
[Bug] No icons

### ISSUE THREAD

**Issue by HamzaETTH** [axodox/unpaint#19]
See screenshot [here](https://i.imgur.com/KNX6Bek.png).

I'm on Windows 10 21H2,

**Comment by PKPenguin321** [comment]
Same issue on 22H2
![image](https://github.com/axodox/unpaint/assets/8345184/c2fb0b91-224a-4ad9-ae5e-c6e289f46d9f)

**Comment by axodox** [comment]
Chris fixed it, I merged it, CI built it, you can download it.
![daft punk](https://media2.giphy.com/media/10IbZpJN1k9D7q/giphy.gif?cid=ecf05e478h4305caopte1mm068x69cnc9qa7re7tswiobq1t&ep=v1_gifs_search&rid=giphy.gif&ct=g)
