### ISSUE TITLE
Question: How to specify custom model folder?

### ISSUE THREAD

**Issue by DmytroSokhach** [axodox/unpaint#29]
I'm not sure where the app was installed after running msix.
Where is the config file or some other way to specify existing models folder?

**Comment by axodox** [comment]
Hi this is an early demo, so there is no option to change the models folder. You can open the model folder using the open model directory button on the model library tab.

**Comment by DmytroSokhach** [comment]
Thank you for prompt reply!

**Comment by DmytroSokhach** [comment]
@axodox wow, I've just realized the app utilizes ONNX format 😂 not *.safetensors. All local models kind of not compatible.

For those who will read this in future, there is a way to convert from *.safetensors to onnx via [Microsoft Olive](https://github.com/microsoft/Olive/tree/main/examples/directml/stable_diffusion)

Maybe worth adding message in UI, like:
![image](https://github.com/axodox/unpaint/assets/2741620/4de94acb-0d53-4ba5-b13f-1dd1c8531bfa)

**Comment by axodox** [comment]
Yes, to be honest, it is likely that the model library page will change anyway. I am looking into submitting the app to MS store, however I think even though there are no models in the app, bundling even this downloader would just beg for problems.

I am considering a solution where models could be shared using magic links, kind of like how right now you can open things like unpaint://inference/create?model=&positive_prompt=a%20nice%20piece%20of%20pie%20on%20a%20plate&negative_prompt=&guidance_strength=7&sampling_steps=15&random_seed=3539199940.
