### ISSUE TITLE
Failed to build the project

### ISSUE THREAD

**Issue by catoxliu** [axodox/unpaint#37]
Follow the steps and installed all required package.
Updated all nuget packages to latest.
Windows 11
Visual Studio 2022 17.6.4

errors:
```
1>pch.cpp
1>C:\workspace\github\unpaint\packages\Axodox.Common.1.0.23\include\Infrastructure\Logger.h(27,48): error C2039: 'format_string': is not a member of 'std'
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\numeric(23): message : see declaration of 'std'
```

**Comment by axodox** [comment]
I have updated VS and it still compiles. Are building using the public nuget packages, or do you use locally built versions? Have you applied any change to the code?

**Comment by catoxliu** [comment]
@axodox , thanks for your quick reply.
> Are building using the public nuget packages, or do you use locally built versions?

using public nuget packages, all update to latest.
![image](https://github.com/axodox/unpaint/assets/18274604/51f45afb-e27b-4f8d-a38a-e269a1c3e983)

> Have you applied any change to the code?

No, just change the certificate as the documentation suggested.
<img width="506" alt="image" src="https://github.com/axodox/unpaint/assets/18274604/d7787b7e-860f-424c-89f8-69d928ef6f40">


All the google results point that compiler should use C++ 20, which I have checked and confirmed
<img width="591" alt="image" src="https://github.com/axodox/unpaint/assets/18274604/19c7ee90-78a5-49ed-a0c8-595dadfce0d4">

Here's the whole build log, there're other errors but all related to the precompiled header.
[unpaint_build.log](https://github.com/axodox/unpaint/files/11900249/unpaint_build.log)

**Comment by catoxliu** [comment]
Some update.

Since you mentioned build the module locally, so I tried to build "axodox-common" as well, having the same error.
So I go to "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\format" to have a look, because according to https://en.cppreference.com/w/cpp/utility/format/basic_format_string, it should be in that header file.

But yeah, it's not there, instead I find the equivelent declaration in that file
```
template <class... _Args>
using _Fmt_string = _Basic_format_string<char, type_identity_t<_Args>...>;
```

So yeah, by replaceing these two line I can get "axodox-common" compiled successfully now
```
     template<typename... TArgs>
-    void log(log_severity severity, const std::format_string<TArgs...> format, TArgs&&... args) const
+    void log(log_severity severity, const std::_Fmt_string<TArgs...> format, TArgs&&... args) const^M
     {
...
     template<typename... TArgs>
-    void log(log_severity severity, const std::wformat_string<TArgs...> format, TArgs&&... args) const
+    void log(log_severity severity, const std::_Fmt_wstring<TArgs...> format, TArgs&&... args) const^M
     {
```

Then I go back to unpaint project and use the same change. Now I only get this error message:
`1>C:\workspace\github\unpaint\Unpaint\SettingsViewModel.cpp(24,40): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'winrt::Unpaint::AdapterViewModel'
1>C:\workspace\github\unpaint\Unpaint\SettingsViewModel.cpp(24,40): message : Invalid aggregate initialization
1>C:\workspace\github\unpaint\Unpaint\SettingsViewModel.cpp(74,5): error C2440: 'return': cannot convert from 'std::wstring' to 'winrt::hstring'
1>C:\workspace\github\unpaint\Unpaint\SettingsViewModel.cpp(74,5): message : No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called`


All this seems to be that I'm not using the right version of MSVC? would you mind to point which version you're using? thanks
