### ISSUE TITLE
'make_guid': identifier not found

### ISSUE THREAD

**Issue by Artuurodrt** [axodox/unpaint#44]
Firstly, congratulations on developing such an impressive project!

I am currently attempting to build this project using Visual Studio 2022, but I am encountering a specific error. Could you possibly provide some insight or guidance on why this might be happening? Any assistance would be greatly appreciated."

![image](https://github.com/axodox/unpaint/assets/63877617/ac616780-8e79-4d53-9c87-e9b2efcd8ef6)

**Comment by axodox** [comment]
Running update_dependencies.ps1 should resolve this.

**Comment by Artuurodrt** [comment]
This worked! Thanks a lot!
