### ISSUE TITLE
Impossible to add stable, diffusion, ONNX schemes on Xbox series S

### ISSUE THREAD

**Issue by Agerald04** [axodox/unpaint#52]
Tried every model under the sun that was stable diffusion ONNX format but kept saying "The model does not match the Stable Diffusion ONNX schema." Tried to import locally said the same thing seems like a possible platform issue then a software issue because of the difference between windows and Xbox windows. But I'm not a expert on that since MS isn't really opened on that but hopefully this is a simple fix either on my part or yours. Or just might be my mistake.

**Comment by axodox** [comment]
Have you tried these?
https://huggingface.co/models?library=onnx&other=stable-diffusion&other=unpaint

**Comment by Agerald04** [comment]
Ya it was a problem on my side
